% -------------------------------------------------------------------
%  Generated by MATLAB on 16-Feb-2021 22:27:21
%  MATLAB version: 9.9.0.1570001 (R2020b) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

I = saveVarsMat.I; % <3024x4032x3 uint8> too many elements

gs = saveVarsMat.gs; % <3024x4032 uint8> too many elements

clear saveVarsMat;
